### ISSUE TITLE
Numerical character didn't align correctly

### ISSUE THREAD

**Issue by aurizasalim** [impallari/Libre-Franklin#16]
As seen in attached screenshot, libre-franklin font in number is not aligned correctly. Compared with Calibri, it supposed to align vertically the same, even though having more "0" character, which is takes more space than "1" character.
I think it would be great if this issue could be fixed. Thank you.
![libre-franklin issue](https://cloud.githubusercontent.com/assets/7480683/19101038/888d4a16-8aee-11e6-9f16-5249099b6211.jpg)

**Comment by impallari** [comment]
Fonts can have 4 different styles for the numbers, [learn more here](http://fontfeed.com/archives/figuring-it-out-osf-lf-and-tf-explained/).
Calibri figures are "Tabular Lining", for LibreFranklin we wanted our figures to be are "Proportional Lining" since it will be mostly used in h1,h2,h3 headlines and they look best in that scenario.
We may add "Tabular Figures" at some point in the future, maybe.

**Comment by davelab6** [comment]
👍

**Comment by efc** [comment]
The link above explaining the typesetting of numbers no longer works. Here is [an explanation in Wikipedia of typesetting numbers](https://en.wikipedia.org/wiki/Typeface#Typesetting_numbers) that describes the same four options.

I find myself wishing LibreFranklin had non-lining (or lower case) numbers, but I understand this is unlikely to ever be added.

**Comment by davelab6** [comment]
@efc do you mean "old style" figures?

**Comment by efc** [comment]
Yes, old style figures. But as I said, not holding my breath for this one. I know it is quite uncommon in san-serif fonts.
