### ISSUE TITLE
Use Git Tagging For Old Versions

### ISSUE THREAD

**Issue by davelab6** [impallari/Libre-Franklin#7]
You have a `/source/Old/` Folder - https://github.com/impallari/Libre-Franklin/tree/master/source/Old - with all previous versions, and this is a simple way of archiving them. 

However, in the `source/` Folder -  https://github.com/impallari/Libre-Franklin/tree/master/source - you have also named the version. 

I propose naming it `LibreFranklin-Romans.glyphs` so that as the project evolves, you don't lose the history of the file each time. 

I also propose using Git Tags to keep track of old versions rather than duplicating them as files, but I expect you'll reject that proposal as too complex :)

**Comment by davelab6** [comment]
Perhaps @crystaltype can do this in her fork :)

**Comment by impallari** [comment]
I like to keep all the old source files in a folder because its easier to access the files that way, in case you need to roll something back.

About not adding the version suffix the latest source file:
I can consider that idea, but in practice it makes it easier for me to know exactly what version of the file I'm editing, and to avoid any possible confusion. Especially when you leave your files resting for some time, and you come back weeks or months later.

**Comment by davelab6** [comment]
Okay cool :) @crystaltype please name the file as you did, with the next version number :)

**Comment by impallari** [comment]
I just uploaded v1.004, making more room for the diacritics and fixing the precomposed fractions.
